/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterAiVideoTeensRouteImport } from './routes/register.ai-video-teens'
import { Route as RegisterAiBusinessGrowthRouteImport } from './routes/register.ai-business-growth'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as AiBusinessGrowthCurriculumRouteImport } from './routes/ai-business-growth.curriculum'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as ProgramsAiVideoTeensCurriculumRouteImport } from './routes/programs_.ai-video-teens.curriculum'
import { Route as ProgramsAiBusinessGrowthCurriculumRouteImport } from './routes/programs_.ai-business-growth.curriculum'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicIndexnowPingRouteImport } from './routes/api/public/indexnow-ping'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterAiVideoTeensRoute = RegisterAiVideoTeensRouteImport.update({
  id: '/register/ai-video-teens',
  path: '/register/ai-video-teens',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAiBusinessGrowthRoute =
  RegisterAiBusinessGrowthRouteImport.update({
    id: '/register/ai-business-growth',
    path: '/register/ai-business-growth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const AiBusinessGrowthCurriculumRoute =
  AiBusinessGrowthCurriculumRouteImport.update({
    id: '/ai-business-growth/curriculum',
    path: '/ai-business-growth/curriculum',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const ProgramsAiVideoTeensCurriculumRoute =
  ProgramsAiVideoTeensCurriculumRouteImport.update({
    id: '/programs_/ai-video-teens/curriculum',
    path: '/programs/ai-video-teens/curriculum',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsAiBusinessGrowthCurriculumRoute =
  ProgramsAiBusinessGrowthCurriculumRouteImport.update({
    id: '/programs_/ai-business-growth/curriculum',
    path: '/programs/ai-business-growth/curriculum',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIndexnowPingRoute = ApiPublicIndexnowPingRouteImport.update({
  id: '/api/public/indexnow-ping',
  path: '/api/public/indexnow-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/ai-business-growth/curriculum': typeof AiBusinessGrowthCurriculumRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/register/ai-business-growth': typeof RegisterAiBusinessGrowthRoute
  '/register/ai-video-teens': typeof RegisterAiVideoTeensRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/indexnow-ping': typeof ApiPublicIndexnowPingRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/programs/ai-business-growth/curriculum': typeof ProgramsAiBusinessGrowthCurriculumRoute
  '/programs/ai-video-teens/curriculum': typeof ProgramsAiVideoTeensCurriculumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/ai-business-growth/curriculum': typeof AiBusinessGrowthCurriculumRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/register/ai-business-growth': typeof RegisterAiBusinessGrowthRoute
  '/register/ai-video-teens': typeof RegisterAiVideoTeensRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/indexnow-ping': typeof ApiPublicIndexnowPingRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/programs/ai-business-growth/curriculum': typeof ProgramsAiBusinessGrowthCurriculumRoute
  '/programs/ai-video-teens/curriculum': typeof ProgramsAiVideoTeensCurriculumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/enquire': typeof EnquireRoute
  '/faq': typeof FaqRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/ai-business-growth/curriculum': typeof AiBusinessGrowthCurriculumRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/register/ai-business-growth': typeof RegisterAiBusinessGrowthRoute
  '/register/ai-video-teens': typeof RegisterAiVideoTeensRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/indexnow-ping': typeof ApiPublicIndexnowPingRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/programs_/ai-business-growth/curriculum': typeof ProgramsAiBusinessGrowthCurriculumRoute
  '/programs_/ai-video-teens/curriculum': typeof ProgramsAiVideoTeensCurriculumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/enquire'
    | '/faq'
    | '/programs'
    | '/sitemap.xml'
    | '/admin/enquiries'
    | '/admin/pricing'
    | '/admin/programs'
    | '/admin/schedules'
    | '/admin/visitors'
    | '/ai-business-growth/curriculum'
    | '/programs/$slug'
    | '/register/ai-business-growth'
    | '/register/ai-video-teens'
    | '/admin/'
    | '/api/public/chat'
    | '/api/public/indexnow-ping'
    | '/api/public/track'
    | '/programs/ai-business-growth/curriculum'
    | '/programs/ai-video-teens/curriculum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/enquire'
    | '/faq'
    | '/programs'
    | '/sitemap.xml'
    | '/admin/enquiries'
    | '/admin/pricing'
    | '/admin/programs'
    | '/admin/schedules'
    | '/admin/visitors'
    | '/ai-business-growth/curriculum'
    | '/programs/$slug'
    | '/register/ai-business-growth'
    | '/register/ai-video-teens'
    | '/admin'
    | '/api/public/chat'
    | '/api/public/indexnow-ping'
    | '/api/public/track'
    | '/programs/ai-business-growth/curriculum'
    | '/programs/ai-video-teens/curriculum'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/enquire'
    | '/faq'
    | '/programs'
    | '/sitemap.xml'
    | '/admin/enquiries'
    | '/admin/pricing'
    | '/admin/programs'
    | '/admin/schedules'
    | '/admin/visitors'
    | '/ai-business-growth/curriculum'
    | '/programs/$slug'
    | '/register/ai-business-growth'
    | '/register/ai-video-teens'
    | '/admin/'
    | '/api/public/chat'
    | '/api/public/indexnow-ping'
    | '/api/public/track'
    | '/programs_/ai-business-growth/curriculum'
    | '/programs_/ai-video-teens/curriculum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  EnquireRoute: typeof EnquireRoute
  FaqRoute: typeof FaqRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AiBusinessGrowthCurriculumRoute: typeof AiBusinessGrowthCurriculumRoute
  RegisterAiBusinessGrowthRoute: typeof RegisterAiBusinessGrowthRoute
  RegisterAiVideoTeensRoute: typeof RegisterAiVideoTeensRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicIndexnowPingRoute: typeof ApiPublicIndexnowPingRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ProgramsAiBusinessGrowthCurriculumRoute: typeof ProgramsAiBusinessGrowthCurriculumRoute
  ProgramsAiVideoTeensCurriculumRoute: typeof ProgramsAiVideoTeensCurriculumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/ai-video-teens': {
      id: '/register/ai-video-teens'
      path: '/register/ai-video-teens'
      fullPath: '/register/ai-video-teens'
      preLoaderRoute: typeof RegisterAiVideoTeensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/ai-business-growth': {
      id: '/register/ai-business-growth'
      path: '/register/ai-business-growth'
      fullPath: '/register/ai-business-growth'
      preLoaderRoute: typeof RegisterAiBusinessGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/ai-business-growth/curriculum': {
      id: '/ai-business-growth/curriculum'
      path: '/ai-business-growth/curriculum'
      fullPath: '/ai-business-growth/curriculum'
      preLoaderRoute: typeof AiBusinessGrowthCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/programs_/ai-video-teens/curriculum': {
      id: '/programs_/ai-video-teens/curriculum'
      path: '/programs/ai-video-teens/curriculum'
      fullPath: '/programs/ai-video-teens/curriculum'
      preLoaderRoute: typeof ProgramsAiVideoTeensCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/ai-business-growth/curriculum': {
      id: '/programs_/ai-business-growth/curriculum'
      path: '/programs/ai-business-growth/curriculum'
      fullPath: '/programs/ai-business-growth/curriculum'
      preLoaderRoute: typeof ProgramsAiBusinessGrowthCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/indexnow-ping': {
      id: '/api/public/indexnow-ping'
      path: '/api/public/indexnow-ping'
      fullPath: '/api/public/indexnow-ping'
      preLoaderRoute: typeof ApiPublicIndexnowPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  EnquireRoute: EnquireRoute,
  FaqRoute: FaqRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AiBusinessGrowthCurriculumRoute: AiBusinessGrowthCurriculumRoute,
  RegisterAiBusinessGrowthRoute: RegisterAiBusinessGrowthRoute,
  RegisterAiVideoTeensRoute: RegisterAiVideoTeensRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicIndexnowPingRoute: ApiPublicIndexnowPingRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ProgramsAiBusinessGrowthCurriculumRoute:
    ProgramsAiBusinessGrowthCurriculumRoute,
  ProgramsAiVideoTeensCurriculumRoute: ProgramsAiVideoTeensCurriculumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
